# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  ApplicationChanged:
    runs-on: ubuntu-latest
    outputs:
      applications: ${{ steps.filter-apps.outputs.applications }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get files changed
        id: get-changed-files
        run: |
          git fetch origin
          files=$(git diff HEAD~1 HEAD --name-only | tr '\n' ' ')
          echo "Files -> $files"
          echo "changed_files=$files" >> $GITHUB_ENV

      - name: Load applications list
        id: load-apps
        run: |
          apps=$(jq -r '.applications[]' .github/workflows/applications.json | tr '\n' ',' | sed 's/,$//')
          echo "Applications: $apps"
          echo "apps=$apps" >> $GITHUB_ENV

      - name: Filter changed applications
        id: filter-apps
        run: |
          changed_apps="[]"
          for app in $(echo $apps | tr ',' ' '); do
            if echo "$changed_files" | grep -q "$app/"; then
              changed_apps=$(echo $changed_apps | jq --arg app "$app" '. + [$app]')
            fi
          done
          echo "Changed Applications: $changed_apps"
          echo "::set-output name=applications::$changed_apps"

      - name: Display filtered applications
        if: ${{ steps.filter-apps.outputs.applications != '[]' }}
        run: |
          echo "Applications to Build: ${{ steps.filter-apps.outputs.applications }}"
      
  Build-App:
    needs: ApplicationChanged
    runs-on: ubuntu-latest
    strategy:
      matrix:
        application: ${{ fromJson(needs.ApplicationChanged.outputs.applications) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Maven Application
        run: |
          echo "Building application: ${{ matrix.application }}"
          cd ${{ matrix.application }}
          mvn clean install

