# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build111:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -f MySQL/pom.xml install

  Build:
    runs-on: ubuntu-latest
    outputs:
      applications: ${{ steps.filter-apps.outputs.applications }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get files changed
        id: get-changed-files
        run: |
          git fetch origin
          files=$(git diff HEAD~1 HEAD --name-only)
          echo "Files -> $files"
          echo "changed_files=$files"

      - name: Load applications list
        id: load-apps
        run: |
          apps=$(jq -r '.applications[]' .github/workflows/applications.json | tr '\n' ',' | sed 's/,$//')
          echo "Applications: $apps"
          echo "apps=$apps" >> $GITHUB_ENV

      - name: Filter changed applications
        id: filter-apps
        run: |
          changed_files=$(echo "${{ env.changed_files }}" | tr ' ' '\n')
          apps_to_build=$(echo "$changed_files" | grep -E "$(echo $apps | tr ',' '|')" | sed -E 's|/.*||' | sort -u)
          applications_list=$(echo $apps_to_build | jq -cR 'split("\n") | map(select(. != ""))')
          if [ -z "$applications_list" ]; then
            applications_list="[]"
          fi
          echo "Filtered applications: $applications_list"
          echo "::set-output name=applications::$applications_list"

      - name: Debug applications output
        run: |
          echo "Applications output: '${{ steps.filter-apps.outputs.applications }}'"


